#!/usr/bin/env bash

set -euo pipefail

export TRAIN_DATA_SIZE=${TRAIN_DATA_SIZE:-2}
export VAL_DATA_SIZE=${VAL_DATA_SIZE:-2}
export GROUP_SIZE=${GROUP_SIZE:-2}
export TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
export ALFWORLD_MAX_STEPS=${ALFWORLD_MAX_STEPS:-2}
export ALFWORLD_HISTORY_LENGTH=${ALFWORLD_HISTORY_LENGTH:-1}
export ALFWORLD_TEACHER_CRITIQUE_MAX_TOKENS=${ALFWORLD_TEACHER_CRITIQUE_MAX_TOKENS:-128}
export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-1024}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-1024}
export MAX_MODEL_LEN=${MAX_MODEL_LEN:-4096}
export STUDENT_GPUS_PER_NODE=${STUDENT_GPUS_PER_NODE:-1}
export TEACHER_GPUS_PER_NODE=${TEACHER_GPUS_PER_NODE:-1}
export STUDENT_TP=${STUDENT_TP:-1}
export TEACHER_TP=${TEACHER_TP:-1}
export AGENT_LOOP_WORKERS=${AGENT_LOOP_WORKERS:-${TRAIN_DATA_SIZE}}
export SAVE_FREQ=${SAVE_FREQ:--1}
export TEST_FREQ=${TEST_FREQ:--1}
export VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN:-false}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-qwen35_text_alfworld_opd_smoke}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
exec bash "${SCRIPT_DIR}/run_qwen35_alfworld_opd.sh" "$@"
